### ISSUE TITLE
hello how do i get the file name of credential downloaded from google console

### ISSUE THREAD

**Issue by vensilver** [PattoMotto/ftx-portfolio-monitoring#1]
hey i do not know how to get the file name of the credential downloaded from google console.

can you help?

**Comment by vensilver** [comment]
Traceback (most recent call last):
  File "c:\Users\HG\Desktop\ftx-master\ftx-portfolio-monitoring-main\start_bot.py", line 2, in <module>
    from pmPortfolioMonitoringBot import PortfolioMonitoringBot
  File "c:\Users\HG\Desktop\ftx-master\ftx-portfolio-monitoring-main\pmPortfolioMonitoringBot.py", line 2, in <module>
    import gsheetHelper as gsheet
  File "c:\Users\HG\Desktop\ftx-master\ftx-portfolio-monitoring-main\gsheetHelper.py", line 14, in <module>
    creds = ServiceAccountCredentials.from_json_keyfile_name(credentialFile, scope)
  File "C:\Python39\lib\site-packages\oauth2client\service_account.py", line 221, in from_json_keyfile_name
    return cls._from_parsed_json_keyfile(client_credentials, scopes,
  File "C:\Python39\lib\site-packages\oauth2client\service_account.py", line 171, in _from_parsed_json_keyfile
    raise ValueError('Unexpected credentials type', creds_type,
ValueError: ('Unexpected credentials type', None, 'Expected', 'service_account')

**Comment by PattoMotto** [comment]
Sorry, I've not create the tutorial yet. I planned to to it.

**Here's the step to get google credential json**
1) create new project https://console.cloud.google.com
2) enable google drive API and google sheet API
3) Create service account
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/1745000/135710224-8389bc53-97b8-40c8-9f64-a494f45f985d.png">
4) Navigate to Keys your new service account > Keys > Create new key
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/1745000/135710283-a1a207e0-96ab-42fe-9ba8-4060ae2b9f99.png">
5) Select json and store to it in the project folder
<img width="881" alt="image" src="https://user-images.githubusercontent.com/1745000/135710340-49b0b1c9-b6fa-4d02-81dc-05197c0107c4.png">
6) Switch back to Details and copy your Email
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/1745000/135710264-c817ebd6-02f8-4ba6-b663-ebf46c26aef7.png">
7) Create new sheet and share with the email from 6)
<img width="654" alt="image" src="https://user-images.githubusercontent.com/1745000/135710383-4dee7430-7a88-4047-94c7-1e64529c1e04.png">


Hope this help @vensilver

**Comment by vensilver** [comment]
> Sorry, I've not create the tutorial yet. I planned to to it.
> 
> **Here's the step to get google credential json**
> 
> 1. create new project https://console.cloud.google.com
> 2. enable google drive API and google sheet API
> 3. Create service account
> 
> <img alt="image" width="1209" src="https://user-images.githubusercontent.com/1745000/135710224-8389bc53-97b8-40c8-9f64-a494f45f985d.png">
> 
> 4) Navigate to Keys your new service account > Keys > Create new key
> <img alt="image" width="1258" src="https://user-images.githubusercontent.com/1745000/135710283-a1a207e0-96ab-42fe-9ba8-4060ae2b9f99.png">
> 
> 5) Select json and store to it in the project folder
> <img alt="image" width="881" src="https://user-images.githubusercontent.com/1745000/135710340-49b0b1c9-b6fa-4d02-81dc-05197c0107c4.png">
> 
> 6) Switch back to Details and copy your Email
> <img alt="image" width="1337" src="https://user-images.githubusercontent.com/1745000/135710264-c817ebd6-02f8-4ba6-b663-ebf46c26aef7.png">
> 
> 7) Create new sheet and share with the email from 6)
> <img alt="image" width="654" src="https://user-images.githubusercontent.com/1745000/135710383-4dee7430-7a88-4047-94c7-1e64529c1e04.png">
> 
> 8) Update configuration
> ```
>     "googleCredential": "project-crypto-currency.json", << file name of credential downloaded from google console
>     "gSheetName": "Portfolio monitoring", << google sheet name
> ```
> 
> Hope this help @vensilver

thank you this works. fine made it to work.
